/**
 * SPX Sculpt Brush Presets
 * Face sculpt, body sculpt, hard surface preset sets
 */

export const BRUSH_PRESETS = {
  // ── Face Sculpt Set ──────────────────────────────────────────────────────────
  "Face: Detail Pass": {
    category: "Face",
    description: "Fine facial detail — pores, wrinkles",
    brushType: "draw_sharp",
    radius: 0.08,
    strength: 0.2,
    autoSmooth: 0.1,
    symmetryX: true,
  },
  "Face: Nose Bridge": {
    category: "Face",
    description: "Define nose bridge and tip",
    brushType: "clay",
    radius: 0.12,
    strength: 0.35,
    autoSmooth: 0.2,
    symmetryX: true,
  },
  "Face: Eye Socket": {
    category: "Face",
    description: "Carve eye sockets",
    brushType: "crease",
    radius: 0.15,
    strength: 0.4,
    autoSmooth: 0.15,
    symmetryX: true,
  },
  "Face: Cheekbones": {
    category: "Face",
    description: "Build up cheekbones",
    brushType: "clay_strips",
    radius: 0.2,
    strength: 0.3,
    autoSmooth: 0.25,
    symmetryX: true,
  },
  "Face: Lips": {
    category: "Face",
    description: "Shape lips",
    brushType: "blob",
    radius: 0.1,
    strength: 0.3,
    autoSmooth: 0.2,
    symmetryX: true,
  },
  "Face: Smooth Skin": {
    category: "Face",
    description: "Smooth skin for SSS",
    brushType: "smooth",
    radius: 0.3,
    strength: 0.5,
    autoSmooth: 0,
    symmetryX: true,
  },
  "Face: Wrinkles": {
    category: "Face",
    description: "Age wrinkles",
    brushType: "crease",
    radius: 0.04,
    strength: 0.25,
    autoSmooth: 0.05,
    symmetryX: false,
  },
  "Face: Ear": {
    category: "Face",
    description: "Ear detail",
    brushType: "clay",
    radius: 0.08,
    strength: 0.3,
    autoSmooth: 0.1,
    symmetryX: false,
  },
  // ── Body Sculpt Set ──────────────────────────────────────────────────────────
  "Body: Muscle Mass": {
    category: "Body",
    description: "Build muscle volume",
    brushType: "clay",
    radius: 0.5,
    strength: 0.4,
    autoSmooth: 0.3,
    symmetryX: true,
  },
  "Body: Muscle Definition": {
    category: "Body",
    description: "Define muscle groups",
    brushType: "crease",
    radius: 0.2,
    strength: 0.3,
    autoSmooth: 0.1,
    symmetryX: true,
  },
  "Body: Chest": {
    category: "Body",
    description: "Chest and pectoral area",
    brushType: "clay_strips",
    radius: 0.4,
    strength: 0.35,
    autoSmooth: 0.2,
    symmetryX: true,
  },
  "Body: Arms": {
    category: "Body",
    description: "Arm musculature",
    brushType: "clay",
    radius: 0.25,
    strength: 0.3,
    autoSmooth: 0.2,
    symmetryX: true,
  },
  "Body: Smooth": {
    category: "Body",
    description: "Overall body smooth pass",
    brushType: "smooth",
    radius: 0.6,
    strength: 0.4,
    autoSmooth: 0,
    symmetryX: true,
  },
  "Body: Fat/Organic": {
    category: "Body",
    description: "Organic soft tissue",
    brushType: "inflate",
    radius: 0.5,
    strength: 0.25,
    autoSmooth: 0.3,
    symmetryX: true,
  },
  // ── Hard Surface Set ─────────────────────────────────────────────────────────
  "Hard: Flat Planes": {
    category: "Hard Surface",
    description: "Create flat surfaces",
    brushType: "flatten",
    radius: 0.5,
    strength: 0.8,
    autoSmooth: 0,
    symmetryX: false,
  },
  "Hard: Panel Lines": {
    category: "Hard Surface",
    description: "Mechanical panel lines",
    brushType: "draw_sharp",
    radius: 0.03,
    strength: 0.6,
    autoSmooth: 0,
    symmetryX: false,
  },
  "Hard: Beveled Edge": {
    category: "Hard Surface",
    description: "Bevel hard edges",
    brushType: "scrape",
    radius: 0.1,
    strength: 0.5,
    autoSmooth: 0,
    symmetryX: false,
  },
  "Hard: Bolt/Rivet": {
    category: "Hard Surface",
    description: "Mechanical details",
    brushType: "blob",
    radius: 0.04,
    strength: 0.5,
    autoSmooth: 0.1,
    symmetryX: false,
  },
  "Hard: Smooth Metal": {
    category: "Hard Surface",
    description: "Polish metal surface",
    brushType: "smooth",
    radius: 0.3,
    strength: 0.6,
    autoSmooth: 0,
    symmetryX: false,
  },
  "Hard: Dents/Damage": {
    category: "Hard Surface",
    description: "Battle damage dents",
    brushType: "grab",
    radius: 0.15,
    strength: 0.5,
    subtract: true,
    autoSmooth: 0.1,
    symmetryX: false,
  },
  // ── Creature Set ─────────────────────────────────────────────────────────────
  "Creature: Scales": {
    category: "Creature",
    description: "Reptile/dragon scales",
    brushType: "blob",
    radius: 0.06,
    strength: 0.4,
    autoSmooth: 0,
    symmetryX: true,
  },
  "Creature: Horns": {
    category: "Creature",
    description: "Build horn shapes",
    brushType: "snake_hook",
    radius: 0.15,
    strength: 0.6,
    autoSmooth: 0.1,
    symmetryX: true,
  },
  "Creature: Claws": {
    category: "Creature",
    description: "Claw tips and details",
    brushType: "pinch",
    radius: 0.08,
    strength: 0.5,
    autoSmooth: 0.05,
    symmetryX: false,
  },
  "Creature: Wrinkled Skin": {
    category: "Creature",
    description: "Aged creature skin",
    brushType: "crease",
    radius: 0.06,
    strength: 0.3,
    autoSmooth: 0.05,
    symmetryX: false,
  },
};

export const BRUSH_PRESET_CATEGORIES = {
  "Face":         Object.keys(BRUSH_PRESETS).filter(k=>BRUSH_PRESETS[k].category==="Face"),
  "Body":         Object.keys(BRUSH_PRESETS).filter(k=>BRUSH_PRESETS[k].category==="Body"),
  "Hard Surface": Object.keys(BRUSH_PRESETS).filter(k=>BRUSH_PRESETS[k].category==="Hard Surface"),
  "Creature":     Object.keys(BRUSH_PRESETS).filter(k=>BRUSH_PRESETS[k].category==="Creature"),
};
